language: ruby
sudo: false
cache: bundler
rvm:
  - jruby-9.1.13.0
  - jruby-1.7.27
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/bc3a12e425e557a6ca23
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
